### PR TITLE
Naufal's Pull Request

### PR DESCRIPTION
**Pull request by Nafachri**
Appointment Design :
1. Styling Appointment Page 
2. Belum menambahkan logic apapun baru mem-fetching data dari database

*kasih tau gua yaa bang rak kalo perlu ada logic besok gua lanjutin

### CODE REVIEW

**Comment by Nafachri** [comment]
Psikiater History Page : 
1. Merubah CSS Pada Card : +Transition, +Shadow, -Button
2. Card Bisa Di Click

**Comment by Nafachri** [comment]
Appointment Page : 
1. Menambahkan logic memilih time schedule
2. Masih ngakalin disabled button dengan popover bootstrap agar user tau dia pilih jadwal itu (MINUS kalo ganti jadwal gabisa)
3. Belom nambahin logic apabila time schedule nya penuh gabisa di click 
4. Belom nambahin logic pilih date yang sesuai dengan jadwal psikiater
5. Ngerapihin styling

**Comment by Nafachri** [comment]
**Form Validation :** 
1. Register Page : Adding validation form for patient/psikiater when they're register
2. Login Page : Adding validation form for patient/psikiater when they're login

**Package that i use for validation  :** 
1. [react-hook-form ](https://react-hook-form.com/)
2. [resolvers yup ](https://react-hook-form.com/get-started#SchemaValidation)

**Appointment Page :** 
1. Adding _"react-loading"_ until data from server already load

**Package that i use for loading screen :** 
1. [react-loading](https://www.npmjs.com/package/react-loading)

**Comment by rakakhrl** [comment]
Untuk minimalisir jumlah dependency pake spinner punya react-bootstrap aja

**Comment by Nafachri** [comment]
Appoitment Page : 
1. Change react-loading with spinner from react-bootstrap

*Form Validation untuk appointment page lupak deadline besok

**Comment by Nafachri** [comment]
commit-an terakhir jangan di merge dulu bang rak

**Comment by Nafachri** [comment]
Appointment Page : 
1. Menambahkan logic untuk pemilihan psikiater date & time schedule
2. Menambahkan Modal pada saat pasien ingin cancel appointment

**Pull request merged**
